services:
  mysql:
    image: mysql:8.0
    container_name: mysql_listsquad
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: listsquad
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_listsquad
    environment:
      PMA_HOST: mysql_listsquad
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 1234
    ports:
      - '8080:80'
    volumes:
      - phpmyadmin_data:/sessions

volumes:
  mysql_data:
  phpmyadmin_data:
